name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - 'Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    branches:
      - '**'
    paths:
      - 'Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

jobs:
  Apple:
    name: Test ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            target: test-macos
          - name: iOS
            target: test-ios
          - name: tvOS
            target: test-tvos
          - name: watchOS
            target: test-watchos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: make ${{ matrix.target }}
        shell: bash
  Linux:
    name: Test Linux
    runs-on: ubuntu-20.04
    container:
      image: swift:5.5.2-focal
    steps:
      - uses: actions/checkout@v2
      - run: swift test
  SPM:
    name: Test with SPM
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install xcaudit
        uses: Alexander-Ignition/XCAudit@main
      - name: Build and test
        run: swift test --enable-code-coverage 2>&1 | xcaudit
        shell: bash
